let exc = RuntimeException("This is the error message");

println("The error message of 'exc' is: ${exc.message}.");

try {
  throw exc;
} catch (RuntimeException : e){ 
  println("Caught exception: ${e.message}.");
} finally {
  println("Finally clean up...\n");
}

println("Testing handling native exception: ");

try { 
  let x = Nil();
} catch(InstantiationException: e){ 
  println("Caught ${e.getClassName()} with message: ${e.message}");
} finally { 
  println("Finally clean up...\n");
}

// throw exc;

class MyException : Exception {
  function __init__(message) {
    super.__init__(message);
    this.message = "MyException error message is: ${message}";
  }
}

// throw MyException("This is the error message of MyException");
