let exc = Exception("This is the error message");

println("The error message of 'exc' is: ${exc.message}.");

try {
  throw exc;
} catch (Exception : e){ 
  println("Caught exception: ${e.message}.");
}

// throw exc;

class MyException : Exception {
  function __init__(message) {
    super.__init__(message);
    this.message = "MyException error message is: ${message}";
  }
}

// throw MyException("This is the error message of MyException");
